import unittest
import os
import tempfile
import json
from uuid import uuid4

from book_builder.models.book import BookProject
from book_builder.commands.storybook_commands import GenerateStorybookPagesCommand
from exporters.export_engine import ExportEngine
from book_builder.models.export import ExportProfile

class TestStorybookIntegration(unittest.TestCase):
    def setUp(self):
        self.project = BookProject(name="Test Storybook")
        self.project.book_type = "Story Book"
        self.project.trim_width_in = 8.5
        self.project.trim_height_in = 8.5
        self.project.has_bleed = True
        
        # Mock Storybook Data
        self.storybook_data = {
            "global_settings": {
                "font_family": "Georgia.ttf",
                "font_size": 24.0
            },
            "pages": [
                {
                    "layout": "title_page",
                    "title": "A Great Adventure",
                    "author": "Antigravity"
                },
                {
                    "layout": "image_top_text_bottom",
                    "text": "Once upon a time in a small village, there lived a brave explorer who loved testing Python.",
                    "image_path": ""
                },
                {
                    "layout": "text_overlay",
                    "text": "They found a magical artifact.",
                    "image_path": ""
                },
                {
                    "layout": "ending_page"
                }
            ]
        }
        self.project.custom_settings["storybook_data"] = self.storybook_data

    def test_generate_storybook_pages(self):
        cmd = GenerateStorybookPagesCommand(self.project)
        success = cmd.execute()
        self.assertTrue(success)
        
        self.assertEqual(len(self.project.pages), 4)
        
        p1 = self.project.pages[0]
        # Title page should have title and author text blocks
        self.assertTrue(any(tb["text"] == "A Great Adventure" for tb in p1.text_blocks))
        self.assertTrue(any(tb["text"] == "By Antigravity" for tb in p1.text_blocks))
        
        p2 = self.project.pages[1]
        self.assertEqual(len(p2.text_blocks), 1)
        self.assertIn("Once upon a time", p2.text_blocks[0]["text"])
        # Should have text wrapping attributes implicitly generated by engine
        # (Though we can't test engine wrap here without rendering, we can test properties)
        self.assertEqual(p2.text_blocks[0]["properties"]["font_name"], "Georgia.ttf")
        self.assertEqual(p2.text_blocks[0]["properties"]["font_size"], 24.0)

    def test_rendering_and_pdf_export(self):
        # Generate pages first
        cmd = GenerateStorybookPagesCommand(self.project)
        cmd.execute()
        
        engine = ExportEngine()
        profile = ExportProfile(
            profile_name="Test PDF",
            export_format="pdf",
            dpi=72,
            color_space="rgb",
            include_crop_marks=False
        )
        
        with tempfile.TemporaryDirectory() as tmpdir:
            profile.custom_options["output_folder"] = tmpdir
            profile.custom_options["naming_template"] = "storybook_test"
            
            try:
                pdf_path = engine.compile_pdf(self.project, profile)
                self.assertTrue(os.path.exists(pdf_path))
                self.assertGreater(os.path.getsize(pdf_path), 1000)
            except Exception as e:
                self.fail(f"PDF Export failed: {e}")

if __name__ == '__main__':
    unittest.main()
